apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tgc-alloy
spec:
  project: alloy
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 0.11.0
      chart: alloy
      helm:
        valueFiles:
          - $values/argocd/alloy/tgc/values.yml
        releaseName: alloy
    - repoURL: "https://github.com/bl4ko/gitops-monitoring"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/bl4ko/gitops-monitoring"
      targetRevision: HEAD
      path: argocd/alloy/tgc/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
