apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: longhorn
spec:
  description: "Longhorn is a distributed block storage system for Kubernetes."
  destinations:
    - namespace: longhorn-system
      server: https://kubernetes.default.svc
  sourceRepos:
    - "https://github.com/bl4ko/gitops-monitoring.git"
  clusterResourceWhitelist:
    - group: ""
      kind: "Namespace"
    - group: "apiextensions.k8s.io"
      kind: "CustomResourceDefinition"
    - group: "rbac.authorization.k8s.io"
      kind: "ClusterRole"
    - group: "rbac.authorization.k8s.io"
      kind: "ClusterRoleBinding"
    - group: "scheduling.k8s.io"
      kind: "PriorityClass"
