apiVersion: v1
kind: Secret
metadata:
  name: longhorn-chart-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: "https://charts.longhorn.io"
  project: "longhorn"
