apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root
spec:
  secretStoreRef:
    name: bitwarden-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: minio-root
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        rootUser: "{{ .MINIO_ROOT_USER }}"
        rootPassword: "{{ .MINIO_ROOT_PASSWORD }}"
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: MINIO_ROOT_USER
    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: MINIO_ROOT_PASSWORD