apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-keys
spec:
  secretStoreRef:
    name: bitwarden-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: secret-keys
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        adminSecretKey: "{{ .MINIO_ADMIN_SECRET_KEY }}"
        remoteUserSecretKey: "{{ .MINIO_REMOTE_USER_SECRET_KEY }}"
  data:
    - secretKey: MINIO_ADMIN_SECRET_KEY
      remoteRef:
        key: MINIO_ADMIN_SECRET_KEY
    - secretKey: MINIO_REMOTE_USER_SECRET_KEY
      remoteRef:
        key: MINIO_REMOTE_USER_SECRET_KEY