apiVersion: v1
kind: Secret
metadata:
  name: prometheus-operator-crds-chart-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: "https://prometheus-community.github.io/helm-charts"
  project: "prometheus-operator-crds"
