apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tgc-kube-prometheus
spec:
  project: kube-prometheus
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      targetRevision: 69.2.2
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/argocd/kube-prometheus/tgc/values.yml
        releaseName: kube-prometheus
    - repoURL: "https://github.com/bl4ko/gitops-monitoring"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/bl4ko/gitops-monitoring"
      targetRevision: HEAD
      path: argocd/kube-prometheus/tgc/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  # syncPolicy:
  #   syncOptions:
  #     - CreateNamespace=true
  #     - ServerSideApply=true
  #     - PruneLast=true
  #   automated:
  #     prune: true
  #     selfHeal: true
