apiVersion: v1
kind: Secret
metadata:
  name: minio-chart-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: "https://charts.min.io"
  project: "minio"
