apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tgc-grafana
spec:
  project: grafana
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 8.10.0
      chart: grafana
      helm:
        valueFiles:
          - $values/argocd/grafana/tgc/values.yml
        releaseName: grafana
    - repoURL: "https://github.com/bl4ko/gitops-monitoring"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/bl4ko/gitops-monitoring"
      targetRevision: HEAD
      path: argocd/grafana/tgc/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
