apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: loki
spec:
  description: |
    loki is a horizontally-scalable, highly-available, multi-tenant log aggregation system inspired by Prometheus.
  destinations:
    - namespace: loki
      server: https://kubernetes.default.svc
  sourceRepos:
    - "https://github.com/bl4ko/gitops-monitoring.git"
    - "https://grafana.github.io/helm-charts"
  clusterResourceWhitelist:
    - group: ""
      kind: "Namespace"
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
