apiVersion: v1
kind: Secret
metadata:
  name: loki-chart-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: "https://grafana.github.io/helm-charts"
  project: "loki"
