apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: microsim-repo
spec:
  secretStoreRef:
    name: bitwarden-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: microsim-repo
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: "https://github.com/bl4ko/gitops-monitoring.git"
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
        project: "microsim"
  data:
    - secretKey: username
      remoteRef:
        key: gitops-repo-user
    - secretKey: password
      remoteRef:
        key: gitops-repo-pat
