apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pbzg-microsim
  namespace: argocd
spec:
  project: microsim
  source:
    repoURL: 'https://github.com/bl4ko/gitops-monitoring.git'
    targetRevision: HEAD
    path: argocd/microsim/overlays/tgc
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: microsim
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true