apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      chart: argo-cd
      targetRevision: "7.8.2"
      helm:
        valueFiles:
          - $values/argocd/argocd/values.yml
        releaseName: argocd
    - repoURL: 'https://github.com/bl4ko/gitops-monitoring.git'
      targetRevision: HEAD
      path: argocd/argocd
      directory:
        recurse: true
        include: "{*.yml,*.yaml}"
    - repoURL: 'https://github.com/bl4ko/gitops-monitoring.git'
      targetRevision: HEAD
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
