apiVersion: v1
kind: Secret
metadata:
  name: argocd-chart-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: "https://argoproj.github.io/argo-helm"
  project: "argocd"
