apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  secretStoreRef:
    name: bitwarden-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        admin-user: "{{ .GRAFANA_ADMIN_USER }}"
        admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
  data:
    - secretKey: GRAFANA_ADMIN_USER
      remoteRef:
        key: GRAFANA_ADMIN_USER
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD