---
- name: Display values for CertManager helm chart
  ansible.builtin.debug:
    msg: "{{ lookup('file', '../../argocd/cert-manager/tgc/values.yml') | from_yaml }}"

- name: Install CertManager with Helm
  kubernetes.core.helm:
    name: cert-manager
    release_namespace: cert-manager
    create_namespace: true
    chart_ref: cert-manager
    chart_repo_url: https://charts.jetstack.io
    state: present
    values: "{{ lookup('file', '../../argocd/cert-manager/tgc/values.yml') | from_yaml }}"
    kubeconfig: "{{ host_kubeconfig_path }}"

- name: Make sure all CertManager pods are healthy and running
  kubernetes.core.k8s_info:
    kubeconfig: "{{ host_kubeconfig_path }}"
    namespace: cert-manager
    kind: Pod
    label_selectors:
      - app.kubernetes.io/instance=cert-manager
    wait: true
    wait_sleep: 10
    wait_timeout: 120

- name: Create ClusterIssuer for external secret's bitwarden sdk (see https://github.com/external-secrets/bitwarden-sdk-server?tab=readme-ov-file#certificates)
  kubernetes.core.k8s:
    namespace: cert-manager
    state: present
    template: "../templates/cert-manager/bitwarden_sdk_issuer.j2"
    kubeconfig: "{{ host_kubeconfig_path }}"

- name: Add secret for acme ClusterIssuer
  kubernetes.core.k8s:
    namespace: cert-manager
    state: present
    template: "../templates/cert-manager/cloudflare_token_secret.j2"
    kubeconfig: "{{ host_kubeconfig_path }}"

- name: Add acme ClusterIssuer
  kubernetes.core.k8s:
    namespace: cert-manager
    state: present
    template: "../templates/cert-manager/acme_issuer.j2"
    kubeconfig: "{{ host_kubeconfig_path }}"
