---
- name: Create external-secrets namespace if not exist
  kubernetes.core.k8s:
    kind: Namespace
    name: external-secrets
    state: present
    kubeconfig: "{{ host_kubeconfig_path }}"

- name: Create secret for bitwarden sdk certs
  kubernetes.core.k8s:
    namespace: external-secrets
    state: present
    template: "../templates/external-secrets/bitwarden_sdk_cert.j2"
    kubeconfig: "{{ host_kubeconfig_path }}"

- name: Display values for external secrets helm chart
  ansible.builtin.debug:
    msg: "{{ lookup('file', '../../argocd/external-secrets/tgc/values.yml') | from_yaml }}"

- name: Install External Secrets with Helm
  kubernetes.core.helm:
    name: external-secrets
    release_namespace: external-secrets
    kubeconfig: "{{ host_kubeconfig_path }}"
    chart_ref: external-secrets
    chart_repo_url: https://charts.external-secrets.io
    state: present
    values: "{{ lookup('file', '../../argocd/external-secrets/tgc/values.yml') | from_yaml }}"

- name: Wait until external secrets pods are ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ host_kubeconfig_path }}"
    namespace: external-secrets
    kind: Pod
    wait: true
    label_selectors:
      - app.kubernetes.io/instance=external-secrets
    wait_sleep: 5
    wait_timeout: 120

- name: Create a bitwarden access token secret
  kubernetes.core.k8s:
    namespace: external-secrets
    state: present
    template: "../templates/external-secrets/bitwarden_access_token.j2"
    kubeconfig: "{{ host_kubeconfig_path }}"

- name: Create a bitwarden ClusterSecretStore from a template
  kubernetes.core.k8s:
    namespace: external-secrets
    state: present
    template: "../templates/external-secrets/bitwarden_cluster_secret_store.j2"
    kubeconfig: "{{ host_kubeconfig_path }}"