apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tgc-mimir
spec:
  project: mimir
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 5.6.0
      chart: mimir-distributed
      helm:
        valueFiles:
          - $values/argocd/mimir/tgc/values.yml
        releaseName: mimir
    - repoURL: "https://github.com/bl4ko/gitops-monitoring"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/bl4ko/gitops-monitoring"
      targetRevision: HEAD
      path: argocd/mimir/tgc/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
