apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-secret
spec:
  secretStoreRef:
    name: bitwarden-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: loki-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        S3_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        S3_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        key: MINIO_REMOTE_USER_SECRET_KEY
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        key: MINIO_REMOTE_USER_ACCESS_KEY