apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: istio
spec:
  description: |
    Istio is an open source service mesh that helps organizations run distributed,
    microservices-based apps anywhere.
  destinations:
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: istio-ingress
      server: https://kubernetes.default.svc
  sourceRepos:
    - "https://github.com/bl4ko/gitops-monitoring.git"
    - "https://istio-release.storage.googleapis.com/charts"
  clusterResourceWhitelist:
    - group: ""
      kind: "Namespace"
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
