apiVersion: v1
kind: Secret
metadata:
  name: istio-chart-repo
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: helm
  url: "https://istio-release.storage.googleapis.com/charts"
  project: "istio"
