# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: tgc-istio-base
# spec:
#   project: istio
#   sources:
#     - repoURL: "https://istio-release.storage.googleapis.com/charts"
#       targetRevision: 1.24.3
#       chart: base
#       helm:
#         valueFiles:
#           - $values/argocd/istio/tgc/base-values.yml
#         releaseName: istio-base
#     - repoURL: "https://github.com/bl4ko/gitops-monitoring"
#       targetRevision: HEAD
#       ref: values
#     - repoURL: "https://github.com/bl4ko/gitops-monitoring"
#       targetRevision: HEAD
#       path: argocd/istio/tgc/resources
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: istio-system
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true
#     automated:
#       prune: true
#       selfHeal: true
