apiVersion: batch/v1
kind: CronJob
metadata:
  name: microsim
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: microsim
            env:
              - name: OTEL_EXPORTER_OTLP_ENDPOINT
                value: "http://alloy.observability.svc.cluster.local:4318/"
              - name: OTEL_EXPORTER_OTLP_INSECURE
                value: "true"
